---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории. 
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
implicit:  
  - В корзине должна быть возможность изменять количество товара (добавлять и убавлять), а так же полностью удалять позицию товара.
  - При заказе нескольких товаров в корзине итоговая сумма должна быть суммирована
  - На сайте должны быть указаны контакты для связи. 
