---
functional:
  - Поиск товаров по ключевому слову или категории 
  - Фильтровать товары
  - Возможность просматривать товары и просматривать подробную информацию о товаре
  - Добавление товаров в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Должен иметь мобильную версию
  - Обработка большого количества трафика
  - Тестирование на совместимость с последними версиями браузера
  - Сайт должен быть доступен на различных устройствах
  - Разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:  
  - Предполагается стабильная и надежная работа сайта
  - Ожидается эффективная работа поиска и фильтрации товаров